#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

rm -rf 0
rm -rf *[1-9]*
# rm -f log.*
rm -f log.foamRun
rm -f log.ehdThrustFoam

rm -rf dynamicCode
# rm -rf constant/polyMesh
rm -rf postProcessing results allResults.dat
rm *.msh *.geo *.pos *~ */*~

cp -ra 0.orig 0

#------------------------------------------------------------------------------
